#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'rprompt'
  overflow = 'hide'

  [[blocks.segments]]
    type = 'shell'
    style = 'plain'
    foreground = 'p:text_color1'
    background = 'transparent'
    template = '<p:orange,transparent>|</> {{ .Name }}<p:orange,transparent>|</>'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    powerline_symbol = ''
    foreground = 'p:text_color2'
    background = 'transparent'
    template = '<p:text_color1></> {{ .FormattedMs }}'

    [blocks.segments.properties]
      always_enabled = true
      style = 'austin'
      threshold = 5000.0

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    invert_powerline = true
    foreground = 'p:text_color3'
    background = 'p:frame_color2'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .CurrentDate | date .Format }} '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:text_color1'
    background = 'transparent'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'text'
    style = 'powerline'
    foreground = 'p:orange'
    background = 'transparent'
    template = ' ❯'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'p:text_color1'
    background = 'transparent'
    template = '[{{.OS}}|{{.HostName}}]-[u:{{.UserName}}]'

  [[blocks.segments]]
    type = 'text'
    style = 'powerline'
    foreground = 'p:orange'
    background = 'transparent'
    template = ' ❯'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    powerline_symbol = ''
    foreground = 'p:text_color1'
    template = '{{ .UpstreamIcon }} {{ .HEAD }}{{if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}{{ if gt .Ahead 0 }} [{{ .Ahead }}<p:git_ahead>↑</>]{{ end }}{{ if gt .Behind 0 }} [{{ .Behind }}<p:git_behind>↓</>]{{ end }}'

    [blocks.segments.properties]
      commit_icon = '@'
      fetch_status = true
      fetch_upstream_icon = true

      [blocks.segments.properties.untracked_modes]
        '/Users/user/Projects/oh-my-posh/' = 'no'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}p:error_color{{end}}', '{{if eq .Code 0}}p:dark_green{{end}}']
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = ['{{if gt .Code 0}}p:error_color{{end}}', '{{if eq .Code 0}}p:dark_green{{end}}']
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = 'p:orange'
  background = 'transparent'
  template = '❯❯ '

[palette]
  bg_color = '#242424'
  black = '#000000'
  blue = '#0000ff'
  cyan = '#00ffff'
  dark_green = '#00a000'
  dark_red = '#a00000'
  error_color = '#e74856'
  fg_color = '#ffffff'
  frame_color1 = '#2e9599'
  frame_color2 = '#0069af'
  git_ahead = '#999900'
  git_behind = '#a54343'
  green = '#00ff00'
  magenta = '#ff00ff'
  orange = '#ff7b00'
  red = '#ff0000'
  text_color1 = '#0099ff'
  text_color2 = '#ffb055'
  text_color3 = '#ffe2c1'
  white = '#ffffff'
  yellow = '#ffff00'
